version: '3.8'

services:

  rabbit:
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      simpleblockchain:
        ipv4_address: 10.1.1.100

  master:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.bootstrap
    networks:
      simpleblockchain:
        ipv4_address: 10.1.1.2
    depends_on:
      - rabbit
    ports:
      - "3000:3000"
    environment:
      - CONNECTION_URL=amqp://guest:guest@10.1.1.100:5672/
      - BLOCK_CAPACITY=5
      - NEIGHBOORS=2
      - BOOTSTRAP=true
      - STAKE=20

  worker1:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.node
    networks:
      simpleblockchain:
        ipv4_address: 10.1.1.3
    depends_on:
      - rabbit
      - master
    ports:
      - "4000:3000"
    environment:
      - CONNECTION_URL=amqp://guest:guest@10.1.1.100:5672/
      - BLOCK_CAPACITY=5
      - NEIGHBOORS=2
      - BOOTSTRAP=false
      - STAKE=20

  worker2:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.node
    networks:
      simpleblockchain:
        ipv4_address: 10.1.1.4
    depends_on:
      - rabbit
      - master
    ports:
      - "8080:3000"
    environment:
      - CONNECTION_URL=amqp://guest:guest@10.1.1.100:5672/
      - BLOCK_CAPACITY=5
      - NEIGHBOORS=2
      - BOOTSTRAP=false
      - STAKE=20

networks:
  simpleblockchain:
    external: true
